"""add_start_end_date_to_schedule

Revision ID: 02840a1d87b2
Revises: 9e49804f78bb
Create Date: 2026-05-19 19:47:46.479654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02840a1d87b2'
down_revision: Union[str, Sequence[str], None] = '9e49804f78bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('end_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'end_date')
    op.drop_column('schedule', 'start_date')
    # ### end Alembic commands ###
