"""Add new fields to course model

Revision ID: 09626c0ca7a0
Revises: 65ec4afc4404
Create Date: 2026-05-13 19:52:00.301013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09626c0ca7a0'
down_revision: Union[str, Sequence[str], None] = '65ec4afc4404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('course', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('course', sa.Column('location', sa.String(), nullable=True))
    op.add_column('course', sa.Column('price_kes', sa.Float(), nullable=True))
    op.add_column('course', sa.Column('price_usd', sa.Float(), nullable=True))
    op.drop_column('course', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('course', 'price_usd')
    op.drop_column('course', 'price_kes')
    op.drop_column('course', 'location')
    op.drop_column('course', 'end_date')
    op.drop_column('course', 'start_date')
    # ### end Alembic commands ###
