"""add curriculum to course

Revision ID: 0a9909ec6d33
Revises: 09626c0ca7a0
Create Date: 2026-05-13 21:03:40.320256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9909ec6d33'
down_revision: Union[str, Sequence[str], None] = '09626c0ca7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('curriculum', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'curriculum')
    # ### end Alembic commands ###
