"""add_currency_to_registration

Revision ID: 2ac876b4c460
Revises: 02840a1d87b2
Create Date: 2026-05-19 23:58:45.392328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac876b4c460'
down_revision: Union[str, Sequence[str], None] = '02840a1d87b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_registration', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('schedule', 'end_date')
    op.drop_column('schedule', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('course_registration', 'currency')
    # ### end Alembic commands ###
