"""add session tracking fields to user model

Revision ID: 4b7aae42d315
Revises: 88a4ee8394ad
Create Date: 2026-06-15 00:05:06.896556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7aae42d315'
down_revision: Union[str, Sequence[str], None] = '88a4ee8394ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_session_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'session_expires_at')
    op.drop_column('user', 'active_session_id')
    # ### end Alembic commands ###
