"""Add created_at to CourseRegistration

Revision ID: 88a4ee8394ad
Revises: d5f1c2a3b4e5
Create Date: 2026-06-05 15:52:58.362043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a4ee8394ad'
down_revision: Union[str, Sequence[str], None] = 'd5f1c2a3b4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_registration', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('newsletter_subscribers_email_key'), 'newsletter_subscribers', type_='unique')
    op.drop_constraint(op.f('newsletter_subscribers_unsubscribe_token_key'), 'newsletter_subscribers', type_='unique')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.drop_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), table_name='newsletter_subscribers')
    op.create_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), 'newsletter_subscribers', ['unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), table_name='newsletter_subscribers')
    op.create_index(op.f('ix_newsletter_subscribers_unsubscribe_token'), 'newsletter_subscribers', ['unsubscribe_token'], unique=False)
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=False)
    op.create_unique_constraint(op.f('newsletter_subscribers_unsubscribe_token_key'), 'newsletter_subscribers', ['unsubscribe_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('newsletter_subscribers_email_key'), 'newsletter_subscribers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('course_registration', 'created_at')
    # ### end Alembic commands ###
