"""create course_registration table

Revision ID: 9e49804f78bb
Revises: 87a5f1a502e5
Create Date: 2026-05-18 23:18:04.005413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e49804f78bb'
down_revision: Union[str, Sequence[str], None] = '87a5f1a502e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('course_title', sa.String(), nullable=False),
    sa.Column('schedule_date', sa.String(), nullable=True),
    sa.Column('schedule_location', sa.String(), nullable=True),
    sa.Column('registration_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('official_email', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('how_heard', sa.String(), nullable=True),
    sa.Column('accommodation', sa.Boolean(), nullable=True),
    sa.Column('airport_pickup', sa.Boolean(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('group_size', sa.String(), nullable=True),
    sa.Column('group_members_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_registration_course_id'), 'course_registration', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_registration_email'), 'course_registration', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_registration_email'), table_name='course_registration')
    op.drop_index(op.f('ix_course_registration_course_id'), table_name='course_registration')
    op.drop_table('course_registration')
    # ### end Alembic commands ###
