"""add_indexes_for_performance

Revision ID: 9ea876ae23b0
Revises: c35dcd109af7
Create Date: 2026-05-20 11:25:10.586474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea876ae23b0'
down_revision: Union[str, Sequence[str], None] = 'c35dcd109af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_course_block_course_id'), 'course_block', ['course_id'], unique=False)
    op.create_index(op.f('ix_schedule_course_id'), 'schedule', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_course_id'), table_name='schedule')
    op.drop_index(op.f('ix_course_block_course_id'), table_name='course_block')
    # ### end Alembic commands ###
