"""add_index_registration_status

Revision ID: c35dcd109af7
Revises: 2ac876b4c460
Create Date: 2026-05-20 11:22:56.144665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35dcd109af7'
down_revision: Union[str, Sequence[str], None] = '2ac876b4c460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_course_registration_status'), 'course_registration', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_registration_status'), table_name='course_registration')
    # ### end Alembic commands ###
