"""Add sub_category to Course

Revision ID: eb603d5337d9
Revises: 9ea876ae23b0
Create Date: 2026-05-21 23:09:36.726276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb603d5337d9'
down_revision: Union[str, Sequence[str], None] = '9ea876ae23b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('sub_category', sa.String(), nullable=True))
    op.create_index(op.f('ix_course_sub_category'), 'course', ['sub_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_sub_category'), table_name='course')
    op.drop_column('course', 'sub_category')
    # ### end Alembic commands ###
